language: python
python:
  - "2.7"
cache:
  pip: true
  directories: 
    - $TRAVIS_BUILD_DIR/docker
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: 'pip install virtualenv'
jobs:
  include:
    - stage: flake8
      script:
        - pip install flake8
        - make flake8
    - stage: build
      script:
        - make DOCKER_TAG=mongodb_consistent_backup:test-3.2 PSMDB_VERSION=3.2 docker
        - make DOCKER_TAG=mongodb_consistent_backup:test-3.4 PSMDB_VERSION=3.4 docker
        - make DOCKER_TAG=mongodb_consistent_backup:test-3.6 PSMDB_VERSION=3.6 docker
        - mkdir -p $TRAVIS_BUILD_DIR/docker
        - docker save mongodb_consistent_backup:test-3.2 >$TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.2.tar
        - docker save mongodb_consistent_backup:test-3.4 >$TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.4.tar
        - docker save mongodb_consistent_backup:test-3.6 >$TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
    - stage: test-cluster-3.6
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.6 test-3.6
    - stage: test-replset-3.6
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6
    - stage: test-cluster-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.4.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.4 test-3.4
    - stage: test-replset-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.4.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 test-3.4
    - stage: test-cluster-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-32.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.2 test-3.2
    - stage: test-replset-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-32.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.2 test-3.2
    - stage: test-archive-none
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6 --archive.method=none
    - stage: test-archive-zbackup
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6 --archive.method=zbackup
#    - stage: test-upload-gs
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6 --upload.method=gs
#    - stage: test-upload-rsync
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6 --upload.method=rsync
#    - stage: test-upload-s3
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.test-3.6.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.6 test-3.6 --upload.method=s3
