language: python
python:
  - "2.7"
cache:
  pip: true
  directories: 
    - $TRAVIS_BUILD_DIR/bin
    - $TRAVIS_BUILD_DIR/docker
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: 'pip install virtualenv flake8'
jobs:
  include:
#    - stage: flake8
#      script:
#        - make flake8
    - stage: build
      script:
        - make docker
        - docker run --rm -it mongodb_consistent_backup:latest --version
        - mkdir -p $TRAVIS_BUILD_DIR/docker
        - docker save mongodb_consistent_backup:latest >$TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
    - stage: test-cluster-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.4
    - stage: test-replset-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4
    - stage: test-cluster-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.2
#    - stage: test-cluster-3.2-sccc
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.2
    - stage: test-replset-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.2
    - stage: test-cluster-3.0
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.0
    - stage: test-replset-3.0
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.0
    - stage: test-archive-none
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=none
    - stage: test-archive-zbackup
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=zbackup
