language: python
python:
  - "2.7"
cache:
  pip: true
  directories: 
    - $TRAVIS_BUILD_DIR/bin
    - $TRAVIS_BUILD_DIR/docker
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: 'pip install virtualenv flake8'
jobs:
  include:
#    - stage: flake8
#      script:
#        - make flake8
    - stage: build
      script:
        - make docker
        - docker run -it mongodb_consistent_backup:latest --version
        - mkdir -p $TRAVIS_BUILD_DIR/docker
        - docker save mongodb_consistent_backup >$TRAVIS_BUILD_DIR/docker/image.tar
    - stage: test-cluster-32
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/image.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/run.sh 3.2
    - stage: test-cluster-34
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/image.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/run.sh 3.4
