language: python
python:
  - "2.7"
cache:
  pip: true
  directories: 
    - $TRAVIS_BUILD_DIR/bin
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: 'pip install virtualenv flake8'
jobs:
  include:
#    - stage: flake8
#      script:
#        - make flake8
    - stage: build
      script:
        - make
        - $TRAVIS_BUILD_DIR/bin/mongodb-consistent-backup --version
    - stage: test-cluster-32
      script:
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/prepare.sh 3.2
        - mkdir -p $TRAVIS_BUILD_DIR/data
        - $TRAVIS_BUILD_DIR/bin/mongodb-consistent-backup --backup.location $TRAVIS_BUILD_DIR/data --backup.name test-cluster-34 --host csReplSet/127.0.0.1:27019,127.0.0.1:27029
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/stop.sh 3.2
    - stage: test-cluster-34
      script:
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/prepare.sh 3.4
        - mkdir -p $TRAVIS_BUILD_DIR/data
        - $TRAVIS_BUILD_DIR/bin/mongodb-consistent-backup --backup.location $TRAVIS_BUILD_DIR/data --backup.name test-cluster-34 --host csReplSet/127.0.0.1:27019,127.0.0.1:27029
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/test-cluster/stop.sh 3.4
