language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install libffi-dev libssl-dev -y
#install: 'pip install "requests[security]"'
script:
# - flake8 --ignore E221,E501 mongodb_consistent_backup
  - make
